---
- include: warmod.yml
  when: csgo_warmod is defined and csgo_warmod
  tags: warmod

- name: CSGO | Install Server Configs
  template:
    src: csgo/server.j2
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/server_{{ item.key }}.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_dict: "{{ csgo_server_instances }}"
  tags: [ 'configs' ]

- name: CSGO | Install esl5on5
  template:
    src: csgo/esl5on5.j2
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/rules_esl5on5.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: CSGO | esl5on5 convenience symlink
  file:
    state: link
    src: "{{ steamcmd_path }}/games/csgo/csgo/cfg/rules_esl5on5.cfg"
    dest: "{{ steamcmd_path }}/games/csgo/csgo/cfg/esl5on5.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: CSGO | Download CSay
  get_url:
    url: "{{ steam_csay_url }}"
    dest: "{{ steamcmd_path }}/games/csgo/csgo_csay.zip"

- name: CSGO | Install CSay
  unarchive:
    copy: no
    creates: "{{ steamcmd_path }}/games/csgo/csgo/addons/CSay.so"
    src: "{{ steamcmd_path }}/games/csgo/csgo_csay.zip"
    dest: "{{ steamcmd_path }}/games/csgo/csgo/"
  become_user: "{{ steamcmd_user }}"

- name: CSGO | Environment Vars Directory
  file:
    state: directory
    path: "{{ steamcmd_path }}/games/csgo/env"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: CSGO | Server Environment Vars
  template:
    src: csgo/systemd-env.j2
    dest: "{{ steamcmd_path }}/games/csgo/env/env_{{ item.key }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_dict: "{{ csgo_server_instances }}"
  tags: [ 'config' ]

- name: CSGO | systemd unit
  template:
    src: csgo/systemd-unit.j2
    dest: /lib/systemd/system/csgo@.service
  tags: [ 'systemd' ]

- name: CSGO | Enable and Start
  service:
    name: "csgo@{{ item.key }}"
    enabled: true
    state: started
  with_dict: "{{ csgo_server_instances }}"
